//------------------------------------------------------------------------------
// <auto-generated>
//     此代码已从模板生成。
//
//     手动更改此文件可能导致应用程序出现意外的行为。
//     如果重新生成代码，将覆盖对此文件的手动更改。
// </auto-generated>
//------------------------------------------------------------------------------

namespace test
{
    using System;
    using System.Collections.Generic;
    
    public partial class Dim_DailyProduct
    {
        public System.Guid DailyProductId { get; set; }
        public System.Guid WarehouseId { get; set; }
        public System.Guid ProductId { get; set; }
        public System.Guid SupplierId { get; set; }
        public decimal SupplierFactor { get; set; }
        public decimal ProductFactor { get; set; }
        public int Disabled { get; set; }
        public System.DateTime Rec_CreateTime { get; set; }
        public string Rec_CreateBy { get; set; }
        public Nullable<System.DateTime> Rec_ModifyTime { get; set; }
        public string Rec_ModifyBy { get; set; }
    }
}
